### ISSUE TITLE
`npm install` not working from `react-todo-app`

### ISSUE THREAD

**Issue by gitaaron** [functionland/fula#136]
Error log -
```
❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-todo-app@0.1.0
npm ERR! Found: graphql@16.3.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"16.3.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"16.2.0" from @functionland/fula-client-react@0.1.6
npm ERR! node_modules/@functionland/fula-client-react
npm ERR!   @functionland/fula-client-react@"~0.1.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/asurty/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asurty/.npm/_logs/2022-04-11T14_13_49_762Z-debug.log
```

**Comment by emadbaqeri** [comment]
Hey @gitaaron, 
The new versions of the npm is very strict about the package management and dependency management.
But by the way when we are using installing some packages that has shared dependencies or you are using both `yarn` and `npm` on a single codebase you are going to face this issue.
I reckon this my be resolver by running `yarn` and installing project dependencies with `yarn`.

**Comment by gitaaron** [comment]
@farhoud the `react-todo-app` directory is clean and I also did a `rush purge` in root of project and also tried from a fresh clone of the repo but still seeing the same error.

I think this is a low priority - just thought it was working without rush ( ? )  Perhaps it has to do with the npm changes you made recently?
