### ISSUE TITLE
replicated orbitdb events are not getting propagated to fula client

### ISSUE THREAD

**Issue by gitaaron** [functionland/fula#159]
## Steps to reproduce

1.  Launch two Boxes (Box0, Box1) in a cluster
2. Connect to Box0 from fsync
3. Launch fuludocs in two different browsers and connect each browser to each Box.
4. Change the text file passed into fsync
5. View the changes updated without refreshing in the browser connected to Box0
6. The changes are not updated in the browser connected to Box1 without refreshing it.

**Comment by mehdibalouchi** [comment]
@gitaaron The parrent commit fixes the issue ([9c6e272](https://github.com/functionland/fula/commit/9c6e2722d7077ab5d1d206272a6da7fbe455973d)).
This one [a709b87](https://github.com/functionland/fula/commit/a709b87b97ba145c6353997478889f79ffb2114b) is for fixing the dependency problem in `fuludocs` (as the commit message says).

**Comment by gitaaron** [comment]
Ah ok thanks - didn't see that commit tied to this issue as there was no issue # in the message
