### ISSUE TITLE
Fula-sec react-native incompatibility (ReferenceError: Can't find variable: BigInt)

### ISSUE THREAD

**Issue by ghorbani-m** [functionland/fula#208]
We have an issue to use the fula-sec package in react-native projects.
The issue is that some fula-sec's dependencies use the BigInt type that react-native does not support.
There is a workaround [here](https://github.com/facebook/react-native/issues/28492#issuecomment-824698934) but it does not work for me, I guess because we used the Hermes engine.
Hermes team is working on [this issue](https://github.com/facebook/hermes/issues/510) as well, and in the future probably Hermes will support BigInt.

**Comment by farhoud** [comment]
@ghorbani-m from my perspective running a cryptographic algorithm on react-native will be near impossible (after you fix this you have to fix the missing secure random generator the list will go on)

@ruffiano89 how much go-fula-sec is feasible?

**Comment by Ruffiano** [comment]
@farhoud if only encryption part then yes, but completely changing .... I have to do some research on go packages

**Comment by ghorbani-m** [comment]
@farhoud  I agree, totally we need to move the encryption layer to the gomobile (go-fula) to encrypt files on the fly while streaming the files.
I am thinking that can we add all fula-sec functionalities to the go-fula project and use them in react-native-fula?
The reason is I don't like to add another .aar file to the Fotos app and increase the size of apk.

**Comment by farhoud** [comment]
@ghorbani-m 
did you try this?
https://github.com/margelo/react-native-bignumber

**Comment by farhoud** [comment]
For random i think you can :
- https://www.npmjs.com/package/expo-random

We are heavily depend on did from ceramic network.
And I don't know if Jamshid can rewrite them in go.
So lets try to run DID usage on js. If we fail we can come up with something.

**Comment by ghorbani-m** [comment]
> @ghorbani-m did you try this?
> 
> * https://github.com/margelo/react-native-bignumber
>   but any way you will be blocked here:
> * https://github.com/StableLib/stablelib/blob/master/packages/random/source/system.ts
>   if no other lib is using web/node crypto api

I don't need use `BigInt `directly in the Fotos, actually, the fula-sec dependencies used BigInt so we can not import fula-sec in a react-native project

**Comment by farhoud** [comment]
@ghorbani-m 
https://github.com/indutny/elliptic us bn.js you can use this:
https://github.com/margelo/react-native-bignumber#as-a-drop-in-replacement
so fula-sec it uses react-native-bignumber instead of using bn.js

**Comment by farhoud** [comment]
If you could provide more info like logs and other things i can be more helpful.

**Comment by ruffiano89** [comment]
Much appreciate if you send us error log
Pls look at this also.
[Fixed Android BigInt Error](https://github.com/digitalcredentials/learner-credential-wallet/pull/51)
https://github.com/facebook/react-native/issues/28492#issuecomment-897732834

**Comment by ghorbani-m** [comment]
I've worked more on this issue and solved the BigInt issue by `rn-nodeify`. 
After that, I got another issue and the root was using etherjs in react-native which needs some [prerequisites ](https://docs.ethers.io/v4/cookbook-react.html#shims)for react-native and finally solved that through `@ethersproject/shims `package.

To get a fast conclusion tried to install etherJs on the Fotos project directly and tried to create a Wallet same as we used in the Fula-sec (`ethers.Wallet.createRandom()`).

It works and I create a wallet programmatically but there is another issue, creating a wallet in [react-native is too slow](https://github.com/ethers-io/ethers.js/issues/2250) and for me takes around 30s!

**Comment by ghorbani-m** [comment]
Finally, I resolved the BigInt issue by rn-nodeify package.
@ruffiano89 
Now I am trying to use the new release of fula-sec (0.6.6) but get an error.

My code:
```javascript
import { FulaDID } from "@functionland/fula-sec"
.
.
.
const fulaDID = new FulaDID();
await fulaDID.create("password", "signiture");
```
Error message:
```
[TypeError: Cannot convert undefined value to object]
```

**Comment by ghorbani-m** [comment]
> Finally, I resolved the BigInt issue by rn-nodeify package. @ruffiano89 Now I am trying to use the new release of fula-sec (0.6.6) but get an error.
> 
> My code:
> 
> ```js
> import { FulaDID } from "@functionland/fula-sec"
> .
> .
> .
> const fulaDID = new FulaDID();
> await fulaDID.create("password", "signiture");
> ```
> 
> Error message:
> 
> ```
> [TypeError: Cannot convert undefined value to object]
> ```

The reason was `crypto.getRandomValues` that has been used in the fula-sec dependencies.

## Solution
We need to add `react-native-get-random-values` package to the project and follow the [rules](https://www.npmjs.com/package/react-native-get-random-values).
