### ISSUE TITLE
fula-client node test fail.

### ISSUE THREAD

**Issue by farhoud** [functionland/fula#213]
command :
`rushx test:node` or `npm run test:node`
exit with error:
```
TAP version 13
not ok 1 Error: no WebRTC support
  ---
    operator: error
    stack: |-
      Error: no WebRTC support
```
There is 2 reason for it:
1. User has to provide wrtc for node in the config
2. If i add wrtc as dev-dependency it will break some browser.

@gitaaron 
Is it okey to add project to rush for testing libp2p against box?

**Comment by gitaaron** [comment]
Sure thanks for the heads up
