### ISSUE TITLE
Change DID Creating Method

### ISSUE THREAD

**Issue by ruffiano89** [functionland/fula#218]

**Comment by ruffiano89** [comment]
@keyvan-m-sadeghi requested removing mnemonic and private keys from DID creation. Alternative solution could be wallet connect #219

**Comment by ruffiano89** [comment]
Request sign to verify user

**Comment by ehsan6sha** [comment]
@ruffiano89 so now the token that is used to encrypt is based on the response from Metamsak?

**Comment by ruffiano89** [comment]
Not only based on metamask sign. User have to insert password as well as.
