### ISSUE TITLE
docker-compose setup for testnet release

### ISSUE THREAD

**Issue by gitaaron** [functionland/fula#222]
Update readme / docker-compose so that this can be pointed to for externals.

- [ ] use ipfs cluster fixed semantic version instead of latest image
- [ ] see why ipfs is build locally and remove if not necessary
- [ ] update ipfs to use semantic version (either in our docker-compose or dockerfile)
- [ ] update our docker-compose to use 'latest' built docker image

blocked by: https://github.com/functionland/fula/issues/217

**Comment by mehdibalouchi** [comment]
@gitaaron I have created [this issue](https://github.com/functionland/fula/issues/217). I think it is related

**Comment by gitaaron** [comment]
> @gitaaron I have created [this issue](https://github.com/functionland/fula/issues/217). I think it is related

good idea - lets  discuss on monday
