### ISSUE TITLE
Graph protocol "graphql" method TypeScript issue

### ISSUE THREAD

**Issue by ghorbani-m** [functionland/fula#32]
In [the Borg interface,](https://github.com/functionland/borg/blob/main/libraries/borg/src/index.ts) the "graphql" method has an issue in the "Variables" parameter.

`graphql: (query: string, variableValues?: never, operationName?: string)`

When we are going to use it in the typescript it just accepts the "undefined" type.

**Comment by emadbaqeri** [comment]
I think I know where the issue is, I'll be working on it.
