### ISSUE TITLE
Create File Uploader Sample

### ISSUE THREAD

**Issue by gitaaron** [functionland/fula#59]
After running the sample:

1.  I connect to the BOX using the PeerId (similar to TODO app).

2. I select a file and click upload and the upload script performs the following steps:

   a ) Invoke the FILE Api to upload the file and receive a CID

   b ) Invoke the DATA Api to add the CID to a `gallery` collection.

3.  I see a success or error message telling me if the upload succeeded.

**Comment by gitaaron** [comment]
I was thinking for this one would it be easy to make it a nodes script?

That way we could also use it for #60

**Comment by farhoud** [comment]
user now can upload using up loader but if you like i can add a node script too

**Comment by gitaaron** [comment]
We are going to include our FULA avatars to make this a little more fun and easy for the reader.  With a node script they can just execute it and see the gallery working without having to upload their own image.

![mehdi-elo](https://user-images.githubusercontent.com/20967/158185289-025d5210-3a78-4026-b928-643ef37b78c0.png)

![aaron-elo](https://user-images.githubusercontent.com/20967/158185321-71374b3d-a52b-40f0-8482-23113848aa18.jpeg)

![farhoud-elo](https://user-images.githubusercontent.com/20967/158185313-40552cfd-2f1d-4b0a-91c6-e8f0eb90842f.png)

**Comment by gitaaron** [comment]
We are going to include our FULA avatars OOB to make it a little more fun and easy for the reader.  With this they will be able to just execute the script instead of choosing their own images to view in the gallery.

[fula-avatars.zip](https://github.com/functionland/fula/files/8245381/fula-avatars.zip)
