### ISSUE TITLE
update sample READMEs

### ISSUE THREAD

**Issue by gitaaron** [functionland/fula#93]
https://github.com/functionland/fula/tree/main/examples/react-gallery - currently based on react starter
https://github.com/functionland/fula/tree/main/examples/react-native - does not exist
https://github.com/functionland/fula/tree/main/examples/react-todo-app - currently based on react starter

**Comment by farhoud** [comment]
I don't know what to do with react-native it need to be archived until our fula-client can work with react-native again!
